import cv2
import numpy as np


def nms(corners_image, radius, threshold):
    # Non Maxima Suppression and thresholding for points generated by the corner detector.
    dilation = cv2.dilate(corners_image, np.ones([2 * radius + 1, 2 * radius + 1]), iterations=1)
    list_of_corners = []

    # exclude points within radius of the image boundary.
    # maxima's value doesn't change after dilation.
    maximas = np.where(dilation[:, :] == corners_image[:, :])
    for x in range(len(maximas[0])):
        i = maximas[0][x]
        j = maximas[1][x]
        if dilation[i, j] > threshold and radius <= i <= dilation.shape[0] - radius and radius <= j <= dilation.shape[1] - radius:
            list_of_corners.append([i, j])

    return list_of_corners
